services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:cached
      - ../.astro:/home/vscode/.astro
      - dist:/home/vscode/dist
      - node_modules:/home/vscode/app/node_modules
    tty: true
    stdin_open: true

volumes:
  .astro:
  dist:
  node_modules:
